### ISSUE TITLE
some icons are hardcoded

### ISSUE THREAD

**Issue by deathtrip** [pedroscaff/swaywsr#10]
So i tried to change the icon for alacritty, and nothing happened after editing the config file.
After investigating, i realised that the icon is hardcoded in [icons.rs](https://github.com/pedroscaff/swaywsr/blob/master/src/icons.rs), along with some others.
This should be handled by the config file, no need to put icons directly into the application.

**Comment by pedroscaff** [comment]
Thanks for the issue.
I checked and understood the problem, if a config file is set and the `awesome` preset is also set, we merge both and if the config file has the same icon as the preset it will be overwritten. I think we could actually not have any preset directly in the application and only put the font awesome presets in the example config file.
If my assumption is correct, to fix your issue you should not mix a config file with icons and the `awesome` preset. so do not use `--config ... --icons awesome` together if you want to overwrite font awesome icons. I'll see if I can do a quick fix later today to change the order and make the config file icons overwrite the preset. I'm happy to accept a PR to remove the hardcoded icons and update the docs :).

**Comment by pedroscaff** [comment]
I fixed the ordering in c07ddf35c2e09180348930af9884f046c93ef768
