### ISSUE TITLE
Import changes from @savchenko's fork

### ISSUE THREAD

**Issue by deathtrip** [pedroscaff/swaywsr#20]
As mentioned in [here](https://github.com/pedroscaff/swaywsr/issues/13#issuecomment-1929059267), i also think some changes should be pulled from his fork, so we have a single repo with all the features. I think the [verbose flag](https://github.com/savchenko/swaywsr/commit/ff4a3c3e6ec42262e4077abeefcae2085d9804ca), and especially the [protected workspaces](https://github.com/savchenko/swaywsr/commit/0ae550103c2d5141fab1c4b4ac98e947e752f302) are most useful. As that's what i currently use to stop certain workspaces from being renamed.

**Comment by GallaisPoutine** [comment]
Hi @deathtrip, 

I've made a Pull Request in order to merge 0ae550103c2d5141fab1c4b4ac98e947e752f302

**Comment by GallaisPoutine** [comment]
Hi @deathtrip, 

Protected workspaces are now integrated within the upstream repository thanks to @pedroscaff. Feel to test it and give us a feedback ! :smile: 

Cheers, 
GallaisPoutine
