### ISSUE TITLE
Add Semantic Release Tags

### ISSUE THREAD

**Issue by pedroscaff** [pedroscaff/swaywsr#39]
see https://github.com/pedroscaff/swaywsr/issues/38

We want to have releases based on tags to allow easy distribution of our software.
Acceptance Criteria:
- Tags should create a github release
- Cargo version should be automatically updated or should be enforced to match the release tag
  - this should protect us from mismatches between release tag and cargo version

**Comment by GallaisPoutine** [comment]
Hi @pedroscaff,

I agree with this. I come from the Linux kernel, and there, Linus updates the Makefile by incrementing the Linux version (either if it is a release candidate or not) and tags the commit.

So here how we should proceed : everytime we update the cargo version (which really corresponds to the software version) we tag and sign it. 

The name of the version in Cargo.toml should be the same as the version in the tag.
The tag should have the following form : "v<ALPHA>.<BETA>.<FIX>[-rcX]", such as the Linux kernel (I find it quite clear and explicit like this).

Do you agree ? If it is the case I will push the tags I did.

**Comment by pedroscaff** [comment]
> Hi @pedroscaff,
> 
> I agree with this. I come from the Linux kernel, and there, Linus updates the Makefile by incrementing the Linux version (either if it is a release candidate or not) and tags the commit.
> 
> So here how we should proceed : everytime we update the cargo version (which really corresponds to the software version) we tag and sign it.
> 
> The name of the version in Cargo.toml should be the same as the version in the tag. The tag should have the following form : "v..[-rcX]", such as the Linux kernel (I find it quite clear and explicit like this).
> 
> Do you agree ? If it is the case I will push the tags I did.

yes agreed! Cargo is the source of truth and the rest should follow it!

**Comment by GallaisPoutine** [comment]
Alright, let's tag, then !

**Comment by GallaisPoutine** [comment]
@pedroscaff done :partying_face:
